
kind: pipeline
name: run

# https://github.com/drone/drone/blob/84f6765defb35f785575446056b598b30760a0f1/cmd/drone-server/inject_runner.go#L69-L76
steps:
  - name: install_and_build
    image: node:8-slim
    resources:
      limits: &resources
        # Always use 'm' or it fails !
        # cpu: "500m"
        memory: "1.5G"
      requests: *resources
    commands:
      - apt-get update && apt-get install -y --no-install-recommends git bzip2
      - yarn install
      # - df -h
      - chmod +x ./node_modules/.bin/nwb
      - $PWD/node_modules/.bin/nwb --version
      - PATH=$PATH:$PWD/node_modules/.bin ./node_modules/.bin/nwb --version
      - yarn nwb-version
      - yarn test
      - exit 1
      - yarn build
      - ls -alh bundle/

  - name: list_build
    image: debian:stable-slim
    commands:
      - ls -alh bundle/
  - name: upload
    image: plugins/gcs
    settings:
      source: bundle/
      target: gs://franchise.geographica.com
      token:
        from_secret: google-token
    # when:
    #   branch:
    #     - master
    #   event:
    #     - push
